config/routes.rb
Rails.application.routes.draw do
  devise_for :students, controllers: { 
  registrations: 'students/registrations',
  sessions: 'students/sessions',
  passwords: 'students/passwords' 
}
  
  # Necessary Student routes and  portfolio routes
  resources :students, only: [:index, :show, :edit, :update, :destroy] do
    resource :portfolio, only: [:show, :edit, :update]  # Nesting portfolio under student
    resources :projects, only: [:index, :new, :create, :show, :edit, :update, :destroy]  # Nesting portfolio under student
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "students#index"
end

app/models/student.rb
class Student < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable

    #using active storage to have one profile picture assoicated
    has_one_attached :profile_picture, dependent: :purge_later 

    #has one relationship and destroy portfolio if student deleted
    #https://guides.rubyonrails.org/v7.1/association_basics.html
    has_one :portfolio, dependent: :destroy

    #after student created create and link portfolio
    after_create :create_portfolio
    #allow editing of portfolio information in form
    accepts_nested_attributes_for :portfolio

    has_many :projects, dependent: :destroy
    
    #Allowed Majors - this is hardcoded for learning 
    # If you wanted an admin for example to update this informatin
    #and not a developer This could be in a scaffolded table
    VALID_MAJORS = ["Computer Engineering BS", "Computer Information Systems BS", "Computer Science BS", "Cybersecurity Major", "Data Science and Machine Learning Major"]

    #validations
    validates :major, inclusion: { in: VALID_MAJORS, message: "%{value} is not a valid major" }
    validates :first_name, :last_name, :major, presence: true
    validate :acceptable_image
    validate :email_format


    private

    #create portfolio when student created
    #https://guides.rubyonrails.org/v7.1/association_basics.html
    def create_portfolio
        #link portfolio to id of student
        Portfolio.create!(student: self, active: false)
    end

    #validate that email is an msudenver email format
    def email_format
        unless email =~ /\A[\w+\-.]+@msudenver\.edu\z/i
            errors.add(:email, "must be an @msudenver.edu email address")
        end
    end


    def acceptable_image
        return unless profile_picture.attached?

        unless profile_picture.blob.byte_size <= 1.megabyte
            errors.add(:profile_picture, "is too big")
        end

        acceptable_types = ["image/jpeg", "image/png"]
        unless acceptable_types.include?(profile_picture.content_type)
            errors.add(:profile_picture, "must be a JPEG or PNG")
        end

    end

end

app/controllers/students/confirmations_controller.rb
# frozen_string_literal: true

class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # Student must be authenticated for edit, update, and destroy actions
  before_action :authenticate_student!, only: %i[ edit update destroy ]

    # Set the @student instance for actions like show, edit, update, destroy
  before_action :set_student, only: %i[show edit update destroy ]
  
  # Logged-in student can only modify their own profile
  before_action :correct_student, only: %i[ edit update destroy ]
  
  #before_action :find_student, only: [:show]

 # GET /students or /students.json
 def index

  # due to error Search Params: #<ActionController::Parameters {"major"=>""} permitted: false>
  #must permitt strong parameters for search so defined search_params
  @search_params = search_params_permitted 

  Rails.logger.info "Controller Search Params: #{@search_params.inspect}"

  #initialize to all students
  #@students = Student.all

 
  #discovered the above will always have the nested search params present
  # if search button clicked commit is "Search"
  #{"search"=>{"major"=>""}, "date_type"=>"", "expected_graduation_date"=>"", "commit"=>"Search"}

  #if show all button clicked commit is "Show All"
  #Parameters: {"search"=>{"major"=>""}, "date_type"=>"", "expected_graduation_date"=>"", "commit"=>"Show All"}
  if (params[:commit] == "Show All")
    Rails.logger.info  "show all"
    @students = Student.all
  #else check searc empty parameters {"search"=>{"major"=>""}, "date_type"=>"", "expected_graduation_date"=>"", "commit"=>"Search"}
  # https://dev.to/kateh/understanding-blank-present-empty-any-and-nil-in-ruby-and-rails-34b4
  elsif @search_params.values.all?(&:blank?)
    # All values are empty or nil
    Rails.logger.info  "All search parameters are empty"
    @students = Student.none
  else
    # At least one value is present so handle search in student model method
    Rails.logger.info  "There are search parameters provided"
    @students = filter_students(@search_params)
  end

   Rails.logger.info "Filtered Students: #{@students.inspect}"

 end


  # GET /students/1 or /students/1.json
  def show
    @student = Student.find(params[:id])
  end


  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
    Rails.logger.info "Students: #{@students.inspect}"
  end

    # Only allow the logged-in student to edit, update, or destroy their own profile
  def correct_student
    unless current_student == @student
      redirect_to root_path, alert: "You are not authorized to modify this profile."
    end
  end

  # Only allow a list of trusted parameters through.
  def student_params
    params.require(:student).permit(:first_name, :last_name, :major, :expected_graduation_date, 
      :profile_picture,
    portfolio_attributes: [:preferred_email, :active, :summary, :skills])
  end

  def search_params_permitted
    #params.require(:search).permit(:major, :expected_graduation_date, :date_type)
    params.fetch(:search, {}).permit(:major, :expected_graduation_date, :date_type)
  end

  def filter_students(search_params)
    Rails.logger.info "Controller Search Params in filter_students: #{search_params.inspect}"
    students = Student.all

    if search_params[:major].present?
      students = students.where(major: search_params[:major])
      Rails.logger.info "Filtered by major: #{search_params[:major]}"
    end

    if search_params[:date_type].present? && search_params[:expected_graduation_date].present?
      #date = Date.parse(search_params[:expected_graduation_date])
      date = search_params[:expected_graduation_date]
      Rails.logger.info "Parsed date: #{date}"

      if search_params[:date_type] == "before"
        students = students.where("expected_graduation_date < ?", date)
        Rails.logger.info "Filtered by date before: #{date}"
      elsif search_params[:date_type] == "after"
        students = students.where("expected_graduation_date > ?", date)
        Rails.logger.info "Filtered by date after: #{date}"
      end
    end

    students
  end



end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>


  <div>
    <%= form.label :major, style: "display: block" %>
    <%= form.select :major, options_for_select(Student::VALID_MAJORS), { prompt: "Select a Major" }, class: "form-control" %>
  </div>

  <div>
    <%= form.label :expected_graduation_date, style: "display: block" %>
    <%= form.date_field :expected_graduation_date %>
  </div>

  <div>
    <%= form.label :profile_picture, style: "display: block" %>
    <%= form.file_field :profile_picture %>
  </div>

<h2>Edit Portfolio Information</h2>

  <%= form.fields_for :portfolio do |portfolio_form| %>
    <div>
      <%= portfolio_form.label :preferred_email %>
      <%= portfolio_form.text_field :preferred_email %>
    </div>

    <div>
      <%= portfolio_form.label :active %>
      <%= portfolio_form.check_box :active %>
    </div>

    <div>
      <%= portfolio_form.label :summary %>
      <%= portfolio_form.text_area :summary %>
    </div>

    <div>
      <%= portfolio_form.label :skills %>
      <%= portfolio_form.text_area :skills %>
    </div>
  <% end %>

  <div>
    <%= form.submit "Update Profile" %>
  </div>
  
<% end %>

app/views/students/_search_form.html.erb
<%= form_with(url: students_path, method: :get, local: true, class: "form-inline", id: "search-form") do |form| %>
    <div>
    <%= form.label :major, "Select Major", class: "form-label" %>
    <%= form.select :major, options_for_select(Student::VALID_MAJORS), { prompt: "Any Major" }, name: 'search[major]', class: "form-control" %>
    </div>

  <div class="col-auto">
    <%= form.label :date_type, "Graduation Date Search", class: "form-label" %>
    <%= form.select :date_type, options_for_select([['Before', 'before'], ['After', 'after']]), { prompt: "Select Option" }, name: 'search[date_type]', class: "form-control" %>
  </div>

  <div class="col-auto">
    <%= form.label :expected_graduation_date, "Date", class: "form-label" %>
    <%= form.date_field :expected_graduation_date, value: params.dig(:search, :expected_graduation_date), name: 'search[expected_graduation_date]', class: "form-control" %>
  </div>
  


  <div>
    <%= form.submit "Search", class: "btn btn-primary"%>
    <%= form.submit "Show All", class: "btn btn-secondary"%>
  </div>


<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>First name:</strong>
    <%= student.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= student.last_name %>
  </p>


  <p>
    <strong>Major:</strong>
    <%= student.major %>
  </p>

  <p>
    <strong>Expected graduation date:</strong>
    <%= student.expected_graduation_date %>
  </p>

  <p>

    <% if student.profile_picture.attached? %>
      <%= image_tag student.profile_picture.variant(resize_to_limit: [150, nil])%>
    <% else %>
      <%= image_tag 'default-profile-picture.jpg', size: "150x150" %>
    <% end %> 
  </p>

  <% if @student.portfolio %>
  <p><strong>Preferred Email:</strong> <%= @student.portfolio.preferred_email %></p>
  <p><strong>Active:</strong> <%= @student.portfolio.active ? 'Yes' : 'No' %></p>
  <p><strong>Summary:</strong> <%= @student.portfolio.summary %></p>
  <p><strong>Skills:</strong> <%= @student.portfolio.skills %></p>
    <h2>Projects:</h2>
    <% if @student.projects.any? %>
      <ul>
        <% @student.projects.each do |project| %>
          <li>
           <%= link_to project.title, student_project_path(@student, project) %><br>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No projects available for this student.</p>
    <% end %>


<%= link_to "Add project", new_student_project_path(@student) %>

<% else %>
  <p>No portfolio information available.</p>
<% end %>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>


<div class="text-bg-primary p-3">Provide summary for employers</div>

<%= render 'search_form', search_params: @search_params %>
<h3>Search Results:</h3>
<% if @students.any? %>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Major</th>
        <th>Graduation Date</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.first_name %></td>
          <td><%= student.last_name %></td>
          <td><%= student.major %></td>
          <td><%= student.expected_graduation_date %></td>
          <td>
            <%= link_to "Show", student_path(student), class: "btn btn-info" %>
            <%= link_to "Edit", edit_student_path(student), class: "btn btn-warning" %>
            <%= link_to "Delete", student, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% elsif @search_params.present? %>
  <p>No students found matching your search criteria.</p>
<% else %>
  <p>Please enter search criteria to find students.</p>
<% end %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> 
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>