config/routes.rb
Rails.application.routes.draw do
  devise_for :students, controllers: { 
  registrations: 'students/registrations',
  sessions: 'students/sessions',
  passwords: 'students/passwords' 
}
  
  # Necessary Student routes and  portfolio routes
  resources :students, only: [:index, :show, :edit, :update, :destroy] do
    resource :portfolio, only: [:show, :edit, :update]  # Nesting portfolio under student
    resources :projects, only: [:index, :new, :create, :show, :edit, :update, :destroy]  # Nesting portfolio under student
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "students#index"
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :student
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: %i[ show edit update destroy ]

  # GET /portfolios or /portfolios.json
  def index
    @portfolios = Portfolio.all
  end

  # GET /portfolios/1 or /portfolios/1.json
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios or /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolio_url(@portfolio), notice: "Portfolio was successfully created." }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1 or /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to portfolio_url(@portfolio), notice: "Portfolio was successfully updated." }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1 or /portfolios/1.json
  def destroy
    @portfolio.destroy!

    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: "Portfolio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def portfolio_params
      params.require(:portfolio).permit(:preferred_email, :active, :summary, :skills, :student_id)
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form.fields_for :portfolio do |portfolio_form| %>
<% if @student.portfolio.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(@student.portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

    <ul>
      <% @student.portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div>
    <%= portfolio_form.label :preferred_email, style: "display: block" %>
    <%= portfolio_form.text_field :preferred_email %>
  </div>

  <div>
    <%= portfolio_form.label :active, style: "display: block" %>
    <%= portfolio_form.check_box :active %>
  </div>

  <div>
    <%= portfolio_form.label :summary, style: "display: block" %>
    <%= portfolio_form.text_area :summary %>
  </div>

  <div>
    <%= portfolio_form.label :skills, style: "display: block" %>
    <%= portfolio_form.text_area :skills %>
  </div>

  <div>
    <%= portfolio_form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<div id="<%= dom_id portfolio %>">
  <p>
    <strong>Preferred email:</strong>
    <%= portfolio.preferred_email %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= portfolio.active %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= portfolio.summary %>
  </p>

  <p>
    <strong>Skills:</strong>
    <%= portfolio.skills %>
  </p>


</div>

app/views/portfolios/edit.html.erb
<h1>Editing portfolio</h1>

<%= render "form", portfolio: @portfolio %>

<br>

<div>
  <%= link_to "Show this portfolio", @portfolio %> |
  <%= link_to "Back to portfolios", portfolios_path %>
</div>

app/views/portfolios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Portfolios</h1>

<div id="portfolios">
  <% @portfolios.each do |portfolio| %>
    <%= render portfolio %>
    <p>
      <%= link_to "Show this portfolio", portfolio %>
    </p>
  <% end %>
</div>

<%= link_to "New portfolio", new_portfolio_path %>

app/views/portfolios/new.html.erb
<h1>New portfolio</h1>

<%= render "form", portfolio: @portfolio %>

<br>

<div>
  <%= link_to "Back to portfolios", portfolios_path %>
</div>

app/views/portfolios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @portfolio %>

<div>
  <%= link_to "Edit this portfolio", edit_portfolio_path(@portfolio) %> |
  <%= link_to "Back to portfolios", portfolios_path %>

  <%= button_to "Destroy this portfolio", @portfolio, method: :delete %>
</div>