config/routes.rb
Rails.application.routes.draw do
  devise_for :students, controllers: { 
  registrations: 'students/registrations',
  sessions: 'students/sessions',
  passwords: 'students/passwords' 
}
  
  # Necessary Student routes and  portfolio routes
  resources :students, only: [:index, :show, :edit, :update, :destroy] do
    resource :portfolio, only: [:show, :edit, :update]  # Nesting portfolio under student
    resources :projects, only: [:index, :new, :create, :show, :edit, :update, :destroy]  # Nesting portfolio under student
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "students#index"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :student
  validates :title, :description, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :get_student
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  #def index
  #  @projects = @student.projects
  #end

  # GET /projects/1 or /projects/1.json
  def show
     @project = @student.projects.find(params[:id])
  end

  # GET /projects/new
  def new
    @project = @student.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = @student.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to student_path(@student), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to student_path(@student), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to student_path(@student), notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = @student.projects.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      #remove id from project params
      params.require(:project).permit(:title, :description)
    end

    def get_student
      @student = Student.find(params[:student_id])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: [@student, @project], local:true) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= project.student_id %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render "form", student: @student, project: @project %>

<br>

<div>
  <%= link_to "Show this project", student_project_path(@student, @project) %> |
  <%= link_to "Back to Student", student_path(@student) %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back", student_path(@student) %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_student_project_path(@student, @project) %> <br>
  <%= button_to "Destroy this project", student_project_path(@student, @project), method: :delete, data: { confirm: "Are you sure?" } %> <br>
  <%= link_to "Back", student_path(@student) %>
</div>